name: Discord Notifications

on:
  push:
    branches:
      - develop
      - "feature/**"
      - "bugfix/**"
      - "fix/**"
      - "enhancement/**"
  pull_request:
    branches:
      - master
      - develop

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            **${{ github.actor }}**
            [${{ github.repository }}] ${{ github.event_name == "push" && "Push to" || "Pull request opened:" }} #${{ github.event.pull_request.number || "" }} ${{ github.event.pull_request.title || github.event.head_commit.message }}
            ${{ github.event.pull_request.body || github.event.head_commit.message }}
            Commit: ${{ github.sha }} | [View changes](${{ github.event.pull_request.html_url || github.event.head_commit.url }})
            